# Site settings
name: 'Septian'
description: "Hello, I'm Septian. I help teams build machine learning on cloud."
meta_description: ''
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
# baseurl: 
production_url: http://septian-putra.github.io/
mailchimp_url: 
cover_image: 'bc_1.jpg'

# Add your GA Tracking Id
# ga_analytics: 'UA-143421382-1'

# Author
author:
  name: 'Septian Gilang Permana Putra'
  image: 'authorimage.jpg'
  greetings: "Hello, I'm Septian."
  description: |
    <strong>Machine Learning Engineer. Full Stack Data Scientist. RaspberryPi hobbyist.</strong><br>
  bio: "Machine Learning Engineer. Full Stack Data Scientist. RaspberryPi hobbyist."

# Contact form setings
email: 'septian-putra@hotmail.com'
contact_page_description: "Looking forward to reading what you have to say!"
thankyou_page_description: "Your message has been successfully sent. I will reply soon."

# Social links
twitter: 'septiangilang_'
#facebook: 'username'
linkedin: 'septian-putra'
github: 'septian-putra'
#codepen: 'username'
medium: '@septiangilang'
#instagram: 'username'
#pinterest: 'username'
#producthunt: '@username'
#rss: 'https://septiangilang.wordpresscom/feed.xml'

# Navigation
navigation:
  - text: About
    url: /about
  - text: Resume
    url: /resume
  - text: Contact Me
    url: /contact  
  # - text: Style-Guide
  #   url: /style-guide


# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

plugins:
  - jemoji

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
